kind: PersistentVolumeClaim

apiVersion: v1
metadata:
  name: pvc001
  annotations: 
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
